#! /usr/bin/env python

import rospy
from bluepy import btle

from geometry_msgs.msg import Pose2D

from numpy import pi
import numpy as np
import struct
import math

import sys

INFO_SERVICE = 0x180A
INFO_MANUF_CHARAC_IN = 0x2A29
INFO_MODEL_CHARAC_IN = 0x2A24
INFO_FIRMW_CHARAC_IN = 0x2A26
DATA_SERVICE = 0x180D
DATA_DATA_CHARA_IN = 0x2A39
DATA_STATU_CHARAC_IN = 0xA001
DATA_DRATE_CHARAC_IN = 0xA002
DATA_SENS_CHARAC_INOUT = 0xA003
DATA_OFFS_CHARAC_INOUT = 0xA007
DATA_CALIB_CHARAC_INOUT = 0xA008
DATA_CORREC_CHARAC_INOUT = 0xA009
DATA_FIRMWC_CHARAC_INOUT = 0xA00A

class delegateNotify(btle.DefaultDelegate):
    battery = 0
    temp = 0
    roll = 0
    pitch = 0
    compass = 0
    def __init__(self):
        btle.DefaultDelegate.__init__(self)

    def handleNotification(self, candle, data):
        global wind
        #print("a notification arrived: %s" %data)
        datab = bytearray(data)
        print(len(datab))
        if(len(datab) == 10):
            w_speed, w_dir, self.battery, self.temp, self.roll, self.pitch, self.compass = struct.unpack('>HHBBBBH',datab)
            w_speed = w_speed/100.0
            w_dir = math.radians(w_dir)
            self.battery = self.battery*10.0
            self.temp = self.temp-100
            self.roll = self.roll - 90
            self.pitch = self.pitch - 90
            wind.theta = w_dir
            wind.x = w_speed*math.cos(w_dir)
            wind.y = w_speed*math.sin(w_dir)

    def getBattery(self):
        return self.battery

    def getTemp(self):
        return self.temp

    def getRoll(self):
        return self.pitch

    def getPitch(self):
        return self.roll

    def getCompass(self):
        return self.compass

if __name__ == "__main__":
    global wind
    rospy.init_node('CalypsoWind', anonymous=True)
    pub = rospy.Publisher('/sailboat/wind', Pose2D, queue_size = 2)

    rate = rospy.Rate(2)
    wind = Pose2D(x = 0, y = 0, theta = 0)

    #if not rospy.has_param('~mac'):
    #    sys.exit("Missing mac param")
    mac_addr = str(rospy.get_param('~mac','E2:7C:BD:0A:22:B6'))

    dev = btle.Peripheral(mac_addr, "random")
    for ser in dev.services:
        print str(ser)

    dev.setDelegate(delegateNotify())
    dataService = dev.getServiceByUUID(btle.UUID(DATA_SERVICE))
    data_charac = dataService.getCharacteristics(DATA_DATA_CHARA_IN)[0]

    print('Turning on sensors')

    sensors_ch = dataService.getCharacteristics(DATA_SENS_CHARAC_INOUT)[0]
    sensors_ch.write(bytes("\01"))

    infoService = dev.getServiceByUUID(btle.UUID(INFO_SERVICE))
    manuf_charac = infoService.getCharacteristics(INFO_MANUF_CHARAC_IN)[0]
    print('Manufacturer : ' + str(manuf_charac.read()))
    model_charac = infoService.getCharacteristics(INFO_MODEL_CHARAC_IN)[0]
    print('Model : ' + str(model_charac.read()))


    ch = dataService.getCharacteristics()[0]
    print(ch.valHandle)
    dev.writeCharacteristic(ch.valHandle+1, "\x01\x00")

    while not rospy.is_shutdown():
        if dev.waitForNotifications(0.5):
            continue
        if(dev.delegate.getBattery() != 0):
            print('Battery left : ' + str(dev.delegate.getBattery()))
        pub.publish(wind)
        rate.sleep()

    dev.writeCharacteristic(ch.valHandle+1, "\x00\x00")
    print('Turning off sensors')
    sensors_ch.write(bytes("\00"))
    dev.disconnect()
