#Header
Header header

#Message type
int64 type

#Repeat indicator
int64 repeat_indic

#MMSI
int64 mmsi

#Navigation status
int64 status

#Rate of turn
int64 rate_of_turn
 
#Speed over ground
int64 speed_over_ground

#Position accuracy
string position_accuracy

#Longitude
float64 longitude

#Latitude
float64 latitude

#Course over ground
int64 course_over_ground

#True heading
int64 heading

#Distance with our boat
float64 distance

